name: Sync All Branches with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:      # Manual trigger

jobs:
  sync-all-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set Git Identity
        run: |
          git config --global user.name "boujuan"
          git config --global user.email "juan.manuel.boullosa.novo@uni-oldenburg.de"
      
      - name: Fetch All from Upstream
        run: |
          git remote add upstream https://github.com/achenry/wind-hybrid-open-controller.git
          git fetch upstream --prune
      
      - name: Get Branch List
        id: branch-list
        run: |
          BRANCHES=$(git branch -r | grep upstream | grep -v HEAD | sed 's/upstream\///' | xargs)
          echo "BRANCHES=$BRANCHES" >> $GITHUB_ENV
          echo "Found branches: $BRANCHES"
      
      - name: Create Sync PRs for Each Branch
        run: |
          for branch in $BRANCHES; do
            echo "Processing branch: $branch"
            
            # Check if branch exists locally, create if not
            if ! git show-ref --verify --quiet refs/heads/$branch; then
              git checkout -b $branch upstream/$branch
              git push -u origin $branch
            else
              # Make sure our local branch is up to date with our fork
              git checkout $branch
              git pull origin $branch
            fi
            
            # Create a sync branch for the PR
            SYNC_BRANCH="sync-upstream-$branch"
            git checkout -B $SYNC_BRANCH upstream/$branch
            
            # Push the sync branch
            git push -f origin $SYNC_BRANCH
            
            # Create PR if it doesn't exist using REST API instead of gh CLI
            PR_DATA="{\"title\":\"Sync $branch branch with upstream\",\"body\":\"This PR syncs the $branch branch with the upstream repository.\",\"head\":\"$SYNC_BRANCH\",\"base\":\"$branch\"}"
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository }}/pulls \
                 -d "$PR_DATA" || echo "PR already exists or couldn't be created for $branch"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
